apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: app
  name: app
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    name: app
status:
  loadBalancer: {}
